### PR TITLE
ci: use Windows 2019 in build-and-test-windows

### LINKED ISSUE #176: CI failed in build-and-test-windows
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run github workflow build-and-test-windows

### 2. What did you expect to see? (Required)

all tests should pass

### 3. What did you see instead (Required)

build-and-test-windows always failed since https://github.com/kcl-lang/kcl-go/commit/16ee99bd07f70a6eef2131668dd3b65c3bbe2e58. It seems that there is some problem with cgo

```
# kcl-lang.io/kcl-go/pkg/kcl_plugin/hello_plugin.test
C:\hostedtoolcache\windows\go\1.19.13\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-425057140\000006.o: in function `_cgo_preinit_init':
\\_\_\runtime\cgo/gcc_libinit_windows.c:40: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-425057140\000006.o: in function `x_cgo_notify_runtime_init_done':
\\_\_\runtime\cgo/gcc_libinit_windows.c:[105](https://github.com/kcl-lang/kcl-go/actions/runs/6609481621/job/17950015784#step:4:106): undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-425057140\000006.o: in function `_cgo_beginthread':
\\_\_\runtime\cgo/gcc_libinit_windows.c:149: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-425057140\000007.o: in function `x_cgo_thread_start':
\\_\_\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
collect2.exe: error: ld returned 1 exit status

# kcl-lang.io/kcl-go/pkg/kcl_plugin.test
FAIL	kcl-lang.io/kcl-go/pkg/kcl_plugin [build failed]
C:\hostedtoolcache\windows\go\1.19.13\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
FAIL	kcl-lang.io/kcl-go/pkg/kcl_plugin/hello_plugin [build failed]
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-1519708659\000006.o: in function `_cgo_preinit_init':
\\_\_\runtime\cgo/gcc_libinit_windows.c:40: undefined reference to `__imp___iob_func'
?   	kcl-lang.io/kcl-go/pkg/kclvm_runtime	[no test files]
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-1519708659\000006.o: in function `x_cgo_notify_runtime_init_done':
\\_\_\runtime\cgo/gcc_libinit_windows.c:105: undefined reference to `__imp___iob_func'
ok  	kcl-lang.io/kcl-go/pkg/logger	0.030s [no tests to run]
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-1519708659\000006.o: in function `_cgo_beginthread':
?   	kcl-lang.io/kcl-go/pkg/path	[no test files]
\\_\_\runtime\cgo/gcc_libinit_windows.c:149: undefined reference to `__imp___iob_func'
ok  	kcl-lang.io/kcl-go/pkg/service	1.047s
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-1519708659\000007.o: in function `x_cgo_thread_start':
ok  	kcl-lang.io/kcl-go/pkg/settings	0.047s
\\_\_\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
?   	kcl-lang.io/kcl-go/pkg/spec/gpyrpc	[no test files]
collect2.exe: error: ld returned 1 exit status
ok  	kcl-lang.io/kcl-go/pkg/tools/format	0.062s
```

### PR DESCRIPTION
**Pull request by jakezhu9**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

fix #176 

#### 2. What is the scope of this PR (e.g. component or file name):

.github/workflow

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

There is a known issue with  C toolchain in windows 2022, which breaks some of our tests. So I change it to use 2019

Ref: https://github.com/golang/go/issues/51007 , https://github.com/DataDog/dd-trace-go/pull/2250

Already tested on my own branch https://github.com/jakezhu9/kcl-go/actions/runs/6732347534

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

### CODE REVIEW

**Review by Peefy — APPROVED** [review]
Good Job! LGTM
